version: '3'
services:
  eurekaserver:
    image: eurekaserver:0.0.0-build.70
    ports: 
      - 8761:8761
    restart: always

  zuulserver:
    depends_on:
      - eurekaserver
    image: zuulserver:0.0.0-build.70
    ports: 
      - 8081:8080
    restart: always

  zookeeper:
    image: zookeeper:0.0.0-build.70
    hostname: zookeeper
    ports:
      - 2181:2181
    restart: always

  kafka:
    depends_on:
      - zookeeper
    image: kafka:0.0.0-build.70
    hostname: kafka
    ports:
      - 9092:9092

  moviedb:
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=6dvpflix
      - MYSQL_DATABASE=moviedb

  userdb:
    image: mariadb
    ports:
      - 13306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=6dvpflix
      - MYSQL_DATABASE=userdb

  movieservice:
    depends_on: 
      - moviedb
      - kafka
      - zuulserver
    image: movieservice:0.0.0-build.70
    ports:
      - 8090:8090
    restart: always

  userservice:
    depends_on: 
      - userdb
      - kafka
      - zuulserver
    image: userservice:0.0.0-build.70
    ports:
      - 8070:8070
    restart: always
