name: Java CI with Maven

on:
  release:
    branches: [ master ]
    types: [created]

# Temporary disabled 
  # pull_request:
  #   branches: [ master ]
  #   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build eurekaserver Maven
      run: mvn -B /eurekaserver --file pom.xml

    - name: Build movieservice Maven
      run: mvn -B /movieservice --file pom.xml
    
    - name: Build userservice Maven
      run: mvn -B /userservice --file pom.xml
